#Define directories 
data_dir= /path/to/fastqs # Define the data directory, explicitly 
work_dir= /path/to/work_dir # Define the working directory, explictly as the directory of this pipeline in the config file
genome_dir= /path/to/genome_dir # Define where the genome index files are located for alignment

metadata_file = /inputs/metadata_file.csv 